- src/components/CancelEditModal/CancelEditModal.tsx
- src/components/CancelEditModal/index.ts
- src/components/ConfirmDeleteModal/ConfirmDeleteModal.tsx
- src/components/ConfirmDeleteModal/index.ts
- src/components/index.ts
- src/hooks/useDeleteList/useDeleteList.tsx
- src/pages/createlist/components/CreateListLayout/CreateListLayout.tsx
- src/pages/editlist/EditListPage.test.tsx
- src/pages/editlist/EditListPage.tsx
- src/pages/listInformation/ListInformationPage.tsx
- test/data/listDetails.refreshed.json
- test/jest/__mock__/stripesComponents.mock.js
- test/mirage/mirage.ts
Added integration of action for edit list page
https://github.com/folio-org/ui-lists/assets/17111248/8c7d4b48-0030-4f08-b693-9f8f273de632
Added new test cases for the edit list page
> Action integration for editlist mode

- jest.config.js
- src/pages/listInformation/ListInformationPage.test.tsx
- test/data/exportStarted.json
- test/mirage/mirage.ts
> Up coverage for exports

- src/pages/editlist/EditListPage.test.tsx
- src/pages/listInformation/ListInformationPage.test.tsx
- src/services/action-menu/helpers.test.ts
- src/services/action-menu/helpers.ts
- test/data/listDetails.refreshed.json
- Fixed issue with disabling button
- Fixed issue when results of previous test leak in next one
> Fix issue with disabling buttons

- CHANGELOG.md
- package.json
- Updated dependency versions to match FOLIO Poppy release.
> Poppy Update

- translations/ui-lists/en.json
> Add new toast message translation

- CHANGELOG.md
- src/pages/editlist/components/EditListResultViewer/EditListResultViewer.tsx
Wrapped with existing div with limited size. 
https://issues.folio.org/browse/UILISTS-41
> UILISTS-41 Edit Query button width incorrect

- src/components/CompilingLoader/CompilingLoader.modult.css
- src/pages/listInformation/ListInformationPage.tsx
> Add css fix for loader width

- src/hooks/useListDetails.ts
- src/pages/listInformation/ListInformationPage.tsx
https://github.com/folio-org/ui-lists/assets/17111248/fff3f9d2-2bcd-4b11-84ce-13e448342f2c
> Add update data after success cancel

- src/components/MainListInfoForm/MainListInfoForm.tsx
- translations/ui-lists/en.json
https://github.com/folio-org/ui-lists/assets/17111248/c0487f57-66cc-4707-9611-e0d31bf56417
> Fix selection of default value

- translations/ui-lists/en.json
Added translation for "export-list.is.inactive" key
> Error message for export of inactive list

- translations/ui-lists/en.json
Added translation keys for [UILISTS-40](https://issues.folio.org/browse/UILISTS-40), [UILISTS-53](https://issues.folio.org/browse/UILISTS-53), [UILISTS-51](https://issues.folio.org/browse/UILISTS-51), [UILISTS-56](https://issues.folio.org/browse/UILISTS-56)
> Added new translation keys for errors

- src/hooks/useCSVListExport/constants.ts
- translations/ui-lists/en.json
- The error message text is updated. 
- The polling delay for export status is reduced from 10 seconds to 3 seconds.
> Update message and delay

- translations/ui-lists/en.json
Addition for [UILISTS-14](https://issues.folio.org/browse/UILISTS-14)
> Add translation for invalid request

- src/pages/listInformation/components/MetaSectionAccordion/MetaSectionAccordion.tsx
Fix for [UILISTS-63](https://issues.folio.org/browse/UILISTS-63)
> Revert changes for list info

- src/components/MainListInfoForm/MainListInfoForm.module.css
- src/components/MainListInfoForm/MainListInfoForm.tsx
- test/jest/__mock__/stripesComponents.mock.js
Implementation for [UILISTS-2](https://issues.folio.org/browse/UILISTS-2) 
Screenshot:
Demo record:
https://github.com/folio-org/ui-lists/assets/17111248/3a997fbd-dd0d-442b-9cae-5b8daff70c92
> Added tooltips for shared private

- src/pages/lists/ListPage.tsx
- src/pages/lists/hooks/useFilters/configurations.ts
- src/pages/lists/hooks/useFilters/helpers.ts
- src/pages/lists/hooks/useFilters/useFilters.test.ts
- src/pages/lists/hooks/useFilters/useFilters.ts
- src/pages/lists/types.ts
- src/utils/helpers.ts
- src/utils/index.ts
Implementation of [UILISTS-10](https://issues.folio.org/browse/UILISTS-10)
- Added default preselected filers
- Changed the design of the reset button 
New button design 
Filters usage demo
https://github.com/folio-org/ui-lists/assets/17111248/4a515f05-1201-4fa5-ab61-3130f6a0b27a
> Added default filters for list landing page

- translations/ui-lists/en.json
- translations/ui-lists/en_US.json
Add 'beta' to app title.
implementation of [UILISTS-71](https://issues.folio.org/browse/UILISTS-71)
> Change app title

- src/components/ListsTable/ListsTable.tsx
Revert @ts-ignore:next-line in lists landing page
> Fix FE build issue

- src/pages/copylist/CopyListPage.test.tsx
- src/pages/copylist/CopyListPage.tsx
- src/pages/createlist/components/MainCreateListForm/MainCreateListForm.module.css
Fix the issue when we try to init refreshes for inactive and lists without query.
> Duplicate list fix

- package.json
Implementation of [UILISTS-77](https://issues.folio.org/browse/UILISTS-77)
> Add qb in to dependencies

- CHANGELOG.md
- src/components/ListsTable/ListsTable.tsx
- src/pages/copylist/CopyListPage.tsx
- src/pages/createlist/CreateListPage.tsx
- src/pages/editlist/EditListPage.tsx
- src/pages/listInformation/ListInformationPage.tsx
- test/jest/__mock__/stripesCore.mock.js
- translations/ui-lists/en.json
https://folio-org.atlassian.net/browse/UILISTS-80
Here we added `TitleManager` to handle title for pages
> UILISTS-80: Update HTML page title on List detail page

- src/hooks/index.ts
- src/hooks/useCSVListExport/useCSVExport.tsx
- src/hooks/useListDetails.ts
- src/hooks/useVisibleColumns/useVisibleColumns.ts
- src/pages/editlist/EditListPage.tsx
- src/pages/listInformation/ListInformationPage.tsx
> [UILISTS-110] Send list of columns when exporting a list

- src/components/ErrorComponent/ErrorComponent.test.tsx
- src/components/ErrorComponent/ErrorComponent.tsx
- src/services/error/error-message-extractor.test.ts
- src/services/error/error-message-extractor.ts
- translations/ui-lists/en.json
When in doubt, optional chain and null coalesce.
> [UILISTS-121] Improve exception handling

- CHANGELOG.md
- package.json
- src/components/CompilingLoader/CompilingLoader.test.tsx
- src/components/ConfigureQuery/ConfigureQuery.test.tsx
- src/components/ListAppIcon/ListAppIcon.test.tsx
- src/components/ListsTable/ListsTable.test.tsx
- src/pages/copylist/CopyListPage.test.tsx
- src/pages/createlist/CreateListPage.test.tsx
- src/pages/lists/ListPage.test.tsx
https://folio-org.atlassian.net/browse/UILISTS-99
We added aXe tests to unit test cases
> UILISTS-99: Lists - Add accessibility testing to automated tests

- src/components/ListsTable/ListsTable.module.css
- src/components/ListsTable/ListsTable.tsx
- src/pages/lists/ListPage.tsx
Implementaion of [UILISTS-136](https://folio-org.atlassian.net/browse/UILISTS-136)
Added logic to pin column headings. 
Demo video
https://github.com/folio-org/ui-lists/assets/17111248/7b03be56-76bd-43b6-b348-ccfefce8469d
> Add pin headings logic

- src/components/MainListInfoForm/MainListInfoForm.tsx
- src/interfaces/entity.ts
Implementation of [UILISTS-150](https://folio-org.atlassian.net/browse/UILISTS-150)
Added custom filtration function to filter by includes instead of startsWith 
Demo
https://github.com/folio-org/ui-lists/assets/17111248/bb417d07-0f14-416a-996d-5072cd707856
> Add custom filter function

- src/components/MainListInfoForm/MainListInfoForm.tsx
Implementation of [UILISTS-150](https://folio-org.atlassian.net/browse/UILISTS-150)
Add logic to ignore case for entity type filtration
https://github.com/folio-org/ui-lists/assets/17111248/62703883-2896-433c-9cac-c9c485b3a5e5
> Add ignore case logic

- src/hooks/useListsPagination/useListsPagination.ts
Fix pagination 
https://github.com/folio-org/ui-lists/assets/17111248/43ae6a38-4fa0-49ab-90dc-ba6255ceeaea
> UILISTS-136: Fix hasNexPage function

- src/index.test.tsx
- src/index.tsx
- src/pages/index.ts
- src/pages/missingperms/MissingAllEntityTypePermissionsPage.module.css
- src/pages/missingperms/MissingAllEntityTypePermissionsPage.tsx
- src/pages/missingperms/index.ts
- translations/ui-lists/en.json
> [UILISTS-128] Add message when attempting to access the lists app with no entity type permissions

- CHANGELOG.md
- src/components/ListsTable/ListsTable.tsx
- src/index.test.tsx
- src/index.tsx
- src/pages/lists/ListPage.tsx
- test/jest/__mock__/stripesComponents.mock.js
- test/jest/__mock__/stripesCore.mock.js
- translations/ui-lists/en.json
Implementation of [UILISTS-137](https://folio-org.atlassian.net/browse/UILISTS-137)
> [UILISTS-137] Add shortcuts modal

- package.json
- src/components/ListsTable/ListsTable.tsx
- src/pages/lists/hooks/useFilters/useFilters.ts
Implementation of [UILISTS-152](https://folio-org.atlassian.net/browse/UILISTS-152)
Update package.json to mape login event work
Optimize the set of total records to fix rerenders 
Demo record: 
https://github.com/user-attachments/assets/0be152cf-16a6-4bd1-9c4c-12e8bb08d853
> [UILISTS-152] Fix session filter behavior

- src/components/ActionMenu/ActionMenu.tsx
- translations/ui-lists/en.json
Fix for [UILISTS-166](https://folio-org.atlassian.net/browse/UILISTS-166)
> [UILISTS-166] Add translation for aria-label

- CHANGELOG.md
- package.json
Implementation of [UILISTS-155](https://folio-org.atlassian.net/browse/UILISTS-155)
> [UILISTS-155] Move stripes-testing in dev dependencies

- src/index.test.tsx
- src/index.tsx
- src/pages/lists/Filters/Filters.tsx
- src/pages/lists/Filters/index.ts
- src/pages/lists/ListPage.tsx
Implementation of [UILISTS-138](https://folio-org.atlassian.net/browse/UILISTS-138)
Demo : 
https://github.com/user-attachments/assets/8b8d9806-97fe-4e7a-a0a2-2e36fd9c4309
> [UILISTS-138] Add wrapper responsible for focus in to filter component

- CHANGELOG.md
- package.json
Fix for [UILISTS-179](https://folio-org.atlassian.net/browse/UILISTS-179)
> [UILISTS-179] Add-resolution-entry

- src/pages/listInformation/components/ListInformationMenu/ListInformationMenu.tsx
- translations/ui-lists/en.json
Implementation of [UILISTS-174](https://folio-org.atlassian.net/browse/UILISTS-174)
Demo: 
https://github.com/user-attachments/assets/7236f663-58fb-453e-8a2a-9081b0bf2011
> [UILISTS-174] Add show columns filter

- src/components/HasCommandWrapper/HasCommandWrapper.tsx
- src/hooks/useKeyCommandsMessages/useKeyCommandsMessages.tsx
- src/index.tsx
- src/pages/editlist/EditListPage.tsx
- src/pages/listInformation/ListInformationPage.tsx
- src/utils/helpers.ts
- src/utils/index.ts
Fix for [UILISTS-158](https://folio-org.atlassian.net/browse/UILISTS-158)
Made small simplification and change typo in EditList page
Now we keep all default commands with errors in the wrapper and rewrite them if receive commands as prop
> [UILISTS-158] Fix two toast per save event

- CHANGELOG.md
- src/components/ListsTable/components/CrossTenantIcon/CrossTenantIcon.css
- src/components/ListsTable/components/CrossTenantIcon/CrossTenantIcon.tsx
- src/components/ListsTable/components/CrossTenantIcon/index.ts
- src/components/ListsTable/components/VisibilityCell/VisibilityCell.tsx
- src/components/ListsTable/components/VisibilityCell/VisibilitySell.tsx
- src/components/ListsTable/components/VisibilityCell/index.ts
- src/components/ListsTable/configs.ts
- src/components/ListsTable/helpers/formatters.tsx
- src/hooks/index.ts
- src/hooks/useCrossTenantCheck/index.ts
- src/hooks/useCrossTenantCheck/useCrossTenantCheck.tsx
- src/interfaces/entity.ts
- translations/ui-lists/en.json
Implementation of [UILISTS-185](https://folio-org.atlassian.net/browse/UILISTS-185)
> [UILISTS-185] Add cross-tenants for list table

- translations/ui-lists/en.json
https://folio-org.atlassian.net/browse/UILISTS-205
Here we add missed translation
> UILISTS-205: Errors when query includes a deleted custom field(follow-up)

- src/hooks/useNavigationBlock/useNavigationBlock.ts
- src/pages/editlist/EditListPage.tsx
https://folio-org.atlassian.net/browse/UILISTS-177
Here is a small fix for the existing implementation.
> UILISTS-177: Prompt for unsaved changes when clicking on the Lists app home from the app context menu (follow-up)

- CHANGELOG.md
- package.json
> Release v3.1.5

- CHANGELOG.md
- src/hooks/useCSVListExport/constants.ts
- src/hooks/useCSVListExport/useCSVExport.tsx
- src/hooks/useCSVListExport/useCSVExportPolling.tsx
- translations/ui-lists/de.json
https://folio-org.atlassian.net/browse/UILISTS-210
Here we increased timeout for toasts during export (begin, success, and fail) to 10 sec.
> UILISTS-210: Toast messages should appear for a longer time during exports

- CHANGELOG.md
- package.json
- src/hooks/useCSVListExport/useCSVExportPolling.tsx
> Release v3.1.6

- CHANGELOG.md
- src/pages/listInformation/components/ListInformationMenu/ListInformationMenu.tsx
https://folio-org.atlassian.net/browse/UILISTS-217
Here we hide the column selection if the list `inactive`
> UILISTS-217: Hide column selection if list is inactive

- src/hooks/useCSVListExport/useCSVExport.tsx
- src/hooks/useCSVListExport/useCSVExportPolling.tsx
[UILISTS-220](https://folio-org.atlassian.net/browse/UILISTS-220)(follow-up)
We made the toast message for the failed export so it doesn't disappear
> UILISTS-220: Make toast message for failed export so it doesn't disappear(follow-up)
