folio-org/ui-lists

.github/workflows/build-npm.yml
Now that dependency `mod-lists` descriptor has been deployed, we can enable publishing UI module descriptor
=> Publish mod descriptor

package.json
- Basic permission group has read access and needs to include this permission to see query results on the List detail page.
- Note that `module.lists.refresh` group inherits from `module.lists.enabled` so it will still have access to this permission.
=> Moving query results GET to basic permission

package.json
This commit switches the entity-types okapi interface from "entity_types" to "entity-types" because it was renamed
=> MODFQMMGR-3 Switch to new "entity-types" interface

src/pages/createlist/components/QueryBuilder/QueryBuilder.module.css, src/pages/createlist/components/QueryBuilder/QueryBuilder.tsx
Fixes [UILISTS-38](https://issues.folio.org/browse/UILISTS-38)
In future, CSS should not use !important override as it can break other parts of FOLIO
=> UILISTS-38 Remove CSS that contained important override

src/pages/lists/ListPage.test.tsx, src/pages/lists/ListPage.tsx, src/pages/lists/hooks/useFilters/useFilters.test.ts, src/pages/lists/hooks/useFilters/useFilters.ts, src/utils/constants.ts
- Fixes [UILISTS-25](https://issues.folio.org/browse/UILISTS-25)
- Renamed `resetAll` to `onResetAll` to match function naming convention
- Added unit tests
- Lint fixes
=> Handle clear filter group properly

package.json
- Fulfills [UILISTS-39](https://issues.folio.org/browse/UILISTS-39)
- No code changes needed since permissions referenced are specific enough. See https://github.com/folio-org/ui-lists/blob/64eeef2a05c8fc5513e2b343383882207c53a9cb/src/utils/constants.ts#L13
=> Make permissions more granular to match new requirements

src/components/ActionMenu/components/ActionsButtonsList/ActionButtonsList.tsx, src/pages/editlist/EditListPage.tsx, src/pages/editlist/components/EditListMenu/EditListMenu.test.tsx, src/pages/editlist/components/EditListMenu/EditListMenu.tsx, src/pages/listInformation/components/ListInformationMenu/ListInformationMenu.tsx
- Fixes issues raised in [UILISTS-39](https://issues.folio.org/browse/UILISTS-39).
- Previously, permissions were not handled on Edit List page. This has now been corrected.
- Added empty element to prevent menu drop-down from displaying if there are no options to select.
- Added a test case to cover new permission logic.
=> Permissions Fix

src/pages/lists/hooks/useFilters/useFilters.ts
- Fixes [UILISTS-25](https://issues.folio.org/browse/UILISTS-25)
- By removing item from list rather than setting to `false`, clear group icon will disappear when no items remain
- Also fixed filter config type definition to be more accurate
=> Fix clear group icon to disappear when no items selected

package.json
- Fixes [UILISTS-52](https://issues.folio.org/browse/UILISTS-52)
- Permission `lists.item.export.cancel` was missing from `module.lists.export` group
=> Add missing cancel export permission

package.json, src/pages/createlist/helpers.ts, src/services/translation/tests/translation.test.tsx, src/services/translation/translation.tsx, translations/ui-lists/en.json
This adds a quick fix to sort record types from the backend.
- added some additional translation infrastructure for [MODFQMMGR-78](https://issues.folio.org/browse/MODFQMMGR-78) (continues this with actual localization)
- fixed a typo (label for the record type dropdown should be "Record type", not "Record types"
=> [UILISTS-61] Sort record types when creating lists

package.json, src/components/ActionMenu/ActionMenu.tsx, src/components/ListsTable/ListsTable.tsx, src/global.d.ts, src/hooks/useRecordsLimit/useRecordsLimit.ts, src/hooks/useRefresh/useInitRefresh/useInitRefresh.ts, tsconfig.json
In the early days of TypeScript in FOLIO, typings for the stripes-* libraries were self-contained within each module.  This was fine when only one or two modules used TypeScript, however, it quickly became unmaintainable, especially when conflicts arose.  We decided to get around this by simply adding a dependence on `@folio/calendar`, but now that `ui-calendar` is removing these typings (https://github.com/folio-org/ui-calendar/pull/508), it's time for us to do so, too.
As a result of all this, we created https://github.com/folio-org/stripes-types as a centralized location for all modules to share their typings.  Since the ones in ui-bulk-edit are now hosted there, they should be removed from the all UI modules themselves.
Remove the dependency and declarations of stripes modules. …
=> [UILISTS-49] Remove dependence on calendar typings

src/interfaces/entity.ts, src/pages/listInformation/ListInformationPage.tsx, src/pages/listInformation/components/ListInformationMenu/ListInformationMenu.test.tsx, src/pages/listInformation/components/ListInformationMenu/ListInformationMenu.tsx, src/pages/listInformation/components/ListInformationResultViewer/ListInformationResultViewer.tsx
The query builder does not provide entity type columns straight from mod-fqm; instead, [it transforms them into a different schema for use in `CheckboxFilter`](https://github.com/folio-org/ui-plugin-query-builder/blob/master/src/QueryBuilder/ResultViewer/helpers.js#L4).  This PR changes the type to use the proper types.
Since the query builder is an external module and does not use typescript, we unfortunately had no way of knowing we were specifying the wrong type.  However, as more of Stripes adds TS typings, we'll be able to catch bugs like this in the future with ease.
=> [UILISTS-92] Fix incorrect types for CheckboxFilter

src/components/ListsTable/ListsTable.tsx
Implementation of [UILISTS-62](https://issues.folio.org/browse/UILISTS-62)
Add logic to track cases when the user is on the empty list landing page and redirect to the last available page.
The list page demands refactoring, so additional tests will be added in [UILISTS-66](https://issues.folio.org/browse/UILISTS-66)
https://github.com/folio-org/ui-lists/assets/17111248/442f3483-2563-4f23-b438-d878b868a891
=> Add redirect from empty page

src/components/ListsTable/ListsTable.tsx, src/components/ListsTable/configs.ts, src/constants/columns.ts
Implementation of [UILISTS-105](https://folio-org.atlassian.net/browse/UILISTS-105)
Added width config for List name, Record type, and Source columns
=> Add column width configuration

src/components/MainListInfoForm/MainListInfoForm.tsx, src/hooks/index.ts, src/hooks/useRecordTypeLabel/index.ts, src/hooks/useRecordTypeLabel/useRecordTypeLabel.tsx, src/pages/editlist/EditListPage.tsx, src/pages/listInformation/ListInformationPage.tsx, src/pages/listInformation/components/MetaSectionAccordion/MetaSectionAccordion.tsx, translations/ui-lists/en.json
Implementation of [UILISTS-98](https://folio-org.atlassian.net/browse/UILISTS-98)
Added entity type to edit page and list details page
=> Add entity type to list details and edit pages

src/components/EditListLayout/EditListLayout.tsx, src/components/EditListResultViewer/EditListResultViewer.tsx, src/pages/copylist/CopyListPage.module.css, src/pages/copylist/CopyListPage.tsx
This was relatively straightforward, abstracting the existing `EditListResultViewer` (responsible for this part on the edit page:
)
=> [UILISTS-75] Show query when duplicating a list

CHANGELOG.md, src/components/EditListResultViewer/EditListResultViewer.tsx, src/pages/listInformation/components/ListInformationResultViewer/ListInformationResultViewer.tsx
[UILISTS-109](https://folio-org.atlassian.net/browse/UILISTS-109)]
Here we pass visible columns to plugin to update query key. Also endpoint `/lists/{listId}/contents` was updated
=> UILISTS-109: Send list of selected columns as parameter to GET /lists/{listId}/contents API

src/components/ActionMenu/ActionMenu.tsx
See [this Slack thread](https://folio-project.slack.com/archives/C210UCHQ9/p1721214369552029); the `DropdownMenu` component requires either both `open` and `onToggle` props, or neither, depending on if it is controlled or not. Since we are controlling it, we must provide both.
We had not realized this error before due to a bug in the underlying types for stripes-components
=> Fix missing prop for controlled DropdownMenu

src/components/ListsTable/ListsTable.tsx, src/hooks/index.ts, src/hooks/useSessionStorage/index.ts, src/hooks/useSessionStorage/useSessionStorage.ts, src/index.test.tsx, src/index.tsx, src/pages/lists/hooks/useFilters/useFilters.ts, test/jest/__mock__/stripesCore.mock.js
Implementation of [UILISTS-152](https://folio-org.atlassian.net/browse/UILISTS-152)
Added logic to keep selected filters on sessionStorage and clean sessionStorage on LOGIN event
Demo record: 
https://github.com/user-attachments/assets/9ea0351b-d667-435b-8060-8c10ad2986b2
=> [UILISTS-152] Add session storage filters

src/components/ListsTable/ListsTable.tsx, src/utils/constants.ts
[UILISTS-152](https://folio-org.atlassian.net/browse/UILISTS-152)
The list table needs to be refactored in the scope of [UILISTS-156](https://folio-org.atlassian.net/browse/UILISTS-156), and logic of tracking items should be moved in a different place and rewritten
Demo of the bug: 
https://github.com/user-attachments/assets/5946ba64-9885-4eb5-95b5-098efde74f27
Demo of the fix: 
https://github.com/user-attachments/assets/ac787e3d-04b3-4a5e-811a-caf739129efa
=> [UILISTS-152] Add additional check for empty filters state inside list table

src/keyboard-shortcuts.tsx
Fix for [UILISTS-137](https://folio-org.atlassian.net/browse/UILISTS-137)
Initially, a logic of replacing keys for Mac and Windows was understood incorrectly in the result; instead of Cmd and Ctrl, should use Mod, and instead of Option, just Alt
Now, replacing work correctly 
How it looks in code: 
How it looks in the App:
=> [UILISTS-137] Fix shortcuts translation

src/components/ListsTable/ListsTable.tsx, src/hooks/useListsPagination/useListsPagination.test.ts, src/hooks/useListsPagination/useListsPagination.ts
Fix for [UILISTS-152](https://folio-org.atlassian.net/browse/UILISTS-152)
The previous version of the fix led to unexpected behavior when we received 0 filter results.
Here, we prevent rerendering through additional checks using the gotToFirstPage method. 
Fix demo: 
https://github.com/user-attachments/assets/1a1c2180-5904-434e-9620-01dc25dd4e7d
=> [UILISTS-152] Fix logic of gotToFirstPage method for ListTable

src/keyboard-shortcuts.tsx, translations/ui-lists/en.json
Addition for [UILISTS-137](https://folio-org.atlassian.net/browse/UILISTS-137)
=> [UILISTS-137] Fix typo in Go to Lists Filter pane shortcut

CHANGELOG.md, src/components/MainListInfoForm/MainListInfoForm.tsx, src/pages/lists/ListPage.tsx, src/pages/lists/RecordTypesFilter/RecordTypesFilter.tsx, src/pages/lists/RecordTypesFilter/RecordTypesFilters.test.tsx, src/pages/lists/RecordTypesFilter/helpers.test.ts, src/pages/lists/RecordTypesFilter/helpers.ts, src/pages/lists/RecordTypesFilter/index.ts, src/pages/lists/constants.ts, src/pages/lists/hooks/useFilterConfig.ts, src/pages/lists/hooks/useFilters/useFilters.ts, src/utils/helpers.test.ts, src/utils/helpers.ts, src/utils/index.ts, test/jest/__mock__/stripesComponents.mock.js, test/jest/__mock__/stripesSmartComponents.mock.js, translations/ui-lists/en.json
Implementation of [UILISTS-145](https://folio-org.atlassian.net/browse/UILISTS-145)
Multiselect record type filter for list page 
Demo record:
https://github.com/user-attachments/assets/bc22e3d8-6799-4602-ab32-67615710d469
=> [UILISTS-145] Add multiselect record types filter

CHANGELOG.md, src/components/EditListResultViewer/EditListResultViewer.tsx, src/components/ListAppIcon/ListAppIcon.test.tsx, src/components/ListsTable/ListsTable.test.tsx, src/hooks/useCSVListExport/useCSVExport.tsx, src/pages/copylist/CopyListPage.test.tsx, src/pages/createlist/CreateListPage.test.tsx, src/pages/editlist/EditListPage.tsx, src/pages/editlist/components/EditListMenu/EditListMenu.test.tsx, src/pages/editlist/components/EditListMenu/EditListMenu.tsx, src/pages/listInformation/ListInformationPage.test.tsx, src/pages/listInformation/ListInformationPage.tsx, src/pages/listInformation/components/ListInformationMenu/ListInformationMenu.test.tsx, src/pages/listInformation/components/ListInformationMenu/ListInformationMenu.tsx, src/pages/lists/ListPage.test.tsx, translations/ui-lists/en.json
Implementation of [UILISTS-157](https://folio-org.atlassian.net/browse/UILISTS-157)
Added logic to export all existing comms or visible columns.
=> [UILISTS-157] Support export of visible columns and export of all columns

src/components/EditListResultViewer/EditListResultViewer.tsx, src/components/EditListResultViewer/EditListResultViewerTest.test.tsx, tsconfig.test.json
An un-memoized call to `JSON.parse` was decoding the `initialValues` on every render of `EditListResultViewer`. As a result, despite any real changes to the `initialValues`, downstream hooks and effects that relied on `initialValues` were reset, causing us to lose state.
This was a hard one to debug, since the problem occurred many levels deeper inside the query builder, and the error only occurred on RTR refreshes, making reproduction slow and tedious. The reason this affected us in this way is that, on RTR refresh, `useOkapiKy` returns an updated `ky` (with a new auth token) and, since `EditListResultViewer` uses this hook, it got rerendered, thus sparking the chain of re-renders.
There will be a companion PR in the query builder to improve memoization, too.
=> [UIPQB-120] Fix Query Builder resetting on RTR refresh

src/pages/createlist/hooks/useCreateListState.ts
Addition to [UILISTS-175](https://folio-org.atlassian.net/browse/UILISTS-175)
Add logic to change visibility back to shared automatically when the user selects the non-cross-tenant type 
Demo record: 
https://github.com/user-attachments/assets/adc5f3b7-bac7-4272-81da-2bd3d518f070
=> [UILISTS-175] Add changing visibility to shared for non cross-tenant lists

CHANGELOG.md, src/pages/createlist/components/CreateListLayout/CreateListLayout.tsx
Supply `contentLabel` to `<Layer>` in `<CreateListLayout>` to avoid a11y warnings in the JS console.
Refs [UILISTS-195](https://folio-org.atlassian.net/browse/UILISTS-195)
=> UILISTS-195 supply a11y props to Layer

CHANGELOG.md, package.json
The real work is being done in https://github.com/folio-org/ui-plugin-query-builder/pull/180; this just adds the new permission required by the query builder.
We need access to `mod-configuration` to retrieve the tenant locale information, as this is not made available by Stripes (Stripes exposes either the tenant locale, or the user locale if one is set, but not both). `mod-fqm-manager` is not aware of user timezones, so queries will always be built with regard to tenant timezone.
=> [UIPQB-126] Use tenant timezone for building queries

CHANGELOG.md, src/global.d.ts
Jira ticket - https://folio-org.atlassian.net/browse/UILISTS-199
`@folio/stripes-acq-components` library does export of types https://github.com/folio-org/stripes-acq-components/blob/master/index.d.ts In turn, the library stores code typing in `@folio/stripes-types` https://github.com/folio-org/stripes-types/tree/master/acq-components .
Modules dependent on `@folio/stripes-acq-components` should not declare `@folio/stripes-acq-components`, as this may cause incorrect assembly at the platform level.
=> UILISTS-199 Remove module declaration for `@folio/stripes-acq-components` in the `global.d.ts` file

CHANGELOG.md, src/hooks/useCrossTenantCheck/useCrossTenantCheck.tsx, src/pages/createlist/hooks/tests/useCreateListState.test.tsx, src/pages/createlist/hooks/useCreateListState.ts
https://folio-org.atlassian.net/browse/UILISTS-198
Here we change the logic for `cross-tenant` visibility changes, after calling `onChange`
https://github.com/user-attachments/assets/9a1fbf6b-0fa4-4f64-b0f4-916a8e7c66f7
=> UILISTS-198: [ESC] The visibility for cross tenant record types changes to "Shared" when the user makes any changes after selecting the entity type

CHANGELOG.md, src/components/ConfigureQuery/ConfigureQuery.tsx
https://folio-org.atlassian.net/browse/UILISTS-161
Here we simply added `catch` block into `queryDetailsDataSource` to use that error in query-plugin-builder to stop polling after 3 attempts.
It should work after https://github.com/folio-org/ui-plugin-query-builder/pull/184 is merged.
https://github.com/user-attachments/assets/4866fc7a-8b08-441f-87d8-7957124043e2
=> UILISTS-161: Stop polling after X attempts result in 500 errors

src/hooks/useNavigationBlock/useNavigationBlock.ts, src/pages/createlist/CreateListPage.test.tsx, src/pages/createlist/components/CreateListLayout/CreateListLayout.tsx, tsconfig.json
https://folio-org.atlassian.net/browse/UILISTS-177
Here small fix for the existing implementation. Modal list saving is unblocked for the redirect.
=> UILISTS-177: Prompt for unsaved changes when clicking on the Lists app home from the app context menu(follow-up)

CHANGELOG.md, src/pages/createlist/hooks/useCreateListState.ts
https://folio-org.atlassian.net/browse/UILISTS-203
Here we removed logic for auto-changing the visibility while creating the list.
https://github.com/user-attachments/assets/2ccad3df-b8f6-4642-9d30-a10ac60bde76
=> UILISTS-203: Don't revert visibility setting when creating a new list

CHANGELOG.md, src/components/ListsTable/ListsTable.tsx, src/components/ListsTable/helpers/formatters.tsx, src/pages/copylist/CopyListPage.test.tsx, src/pages/copylist/CopyListPage.tsx, src/pages/editlist/EditListPage.test.tsx, src/pages/editlist/EditListPage.tsx, src/pages/listInformation/ListInformationPage.test.tsx, src/pages/listInformation/ListInformationPage.tsx
https://folio-org.atlassian.net/browse/UILISTS-211
Here we updated the logic of `searchParams` to store it in `URL`, to prevent problems with restoring the state of `filters` and `offset`
https://github.com/user-attachments/assets/55320583-b2da-44db-812c-7ed48a484729
=> UILISTS-211: The filters reset after closing list on nth pages

CHANGELOG.md, src/components/MainListInfoForm/MainListInfoForm.module.css
https://folio-org.atlassian.net/browse/UILISTS-212
Here we increased the size of `record type` dropdown
was: 
became:
=> UILISTS-212: Increase the width of the record type dropdown

CHANGELOG.md, src/hooks/useNavigationBlock/useNavigationBlock.test.ts, src/hooks/useNavigationBlock/useNavigationBlock.ts, src/pages/copylist/CopyListPage.test.tsx, src/pages/copylist/CopyListPage.tsx, src/pages/editlist/EditListPage.tsx
https://folio-org.atlassian.net/browse/UILISTS-207
We added a prompt modal for unsaved changes while duplicating the list. The navigation path was also fixed.
https://github.com/user-attachments/assets/24a1842d-4ff2-4d80-982e-eae535485443
=> UILISTS-207: Prompt for unsaved changes when we duplicate the list

CHANGELOG.md, src/pages/createlist/CreateListPage.tsx, src/pages/createlist/components/CreateListLayout/CreateListLayout.tsx, src/pages/createlist/components/CreateListLayout/tests/CreateListLayout.test.tsx
https://folio-org.atlassian.net/browse/UILISTS-216
We fixed the prompt for unsaved changes for the create list flow.
=> UILISTS-216: Unsaved changes message prompt interrupts redirect link

CHANGELOG.md, src/components/ConfigureQuery/ConfigureQuery.tsx, src/components/EditListResultViewer/EditListResultViewer.tsx, src/pages/editlist/EditListPage.tsx
Relies on https://github.com/folio-org/ui-plugin-query-builder/pull/235; see explanation there.
=> [UILISTS-222] Prevent incorrectly showing unsaved changes prompt on edit

CHANGELOG.md, src/hooks/useCSVListExport/useCSVExport.tsx, src/hooks/useCSVListExport/useCSVExportPolling.tsx
[UILISTS-220](https://folio-org.atlassian.net/browse/UILISTS-220)
Here we increased the time for the error toast for an unlimited time, till the user dismisses the toast
=> UILISTS-220: Make toast message for failed export so it doesn't disappear

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UILISTS-226
According to the `mod-configuration` decommission and the absence of usage of this interface (`configuration`), the permission is redundant and should be removed.
=> UILISTS-226 Update permission sets to not use the mod-configuration permission
